### ISSUE TITLE
when updating lets remove all `-test` namespaces which were created by fabric8-init-tenant

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-init-tenant#107]
we should iterate through all the users projects which are named `*-test` and remove any which are annotated with 
```yaml
metadata:
  annotations:
    openshift.io/requester: devtools-sre
```
